spring:
  application:
    name: Student-Attendance
  profiles:
    active: dev
  datasource:
    url: "${DATABASE_URL:jdbc:postgresql://localhost:5432/attendance_db}"
    username: "${DB_USER:root}"
    password: "${DB_PASSWORD:shubham}"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081

logging:
  file:
    name: logs/spring.log
  level:
    root: INFO
    com.AS.Student_Attendance: INFO